from minesweeper import Minesweeper, MinesweeperAI, Sentence
bala = Sentence(((1,2),(1,3)),1)
ml = Sentence(((1,2),(1,3),(0,3)),1)
new = Minesweeper()
ai = MinesweeperAI()
new.print()
move = (0,0)
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
cell = ai.make_safe_move()
print(cell)
print()
move = (3,4)
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
cell = ai.make_safe_move()
print(cell)
print()
move = (3,5)
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
cell = ai.make_safe_move()
print(cell)
print()
move = (3,6)
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
print(ai.make_safe_move())
print()
move = (2,5)
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
print(ai.make_safe_move())
print()
move = ai.make_safe_move()
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
print(ai.make_safe_move())
print()
move = ai.make_safe_move()
ai.add_knowledge(move, new.nearby_mines(move))
for sentence in ai.knowledge:
    print(sentence)
print(ai.moves_made)
print(ai.mines)
print(ai.safes)
print(ai.make_safe_move())
print()


